crossdock:
    build: .
    links:
        - alpha
        - omega
    environment:
      - CROSSDOCK_WAIT_FOR=alpha,omega

      - CROSSDOCK_AXIS_CLIENT=alpha,omega
      - CROSSDOCK_AXIS_SERVER=alpha,omega
      - CROSSDOCK_AXIS_TRANSPORT=http,tchannel

      - CROSSDOCK_BEHAVIOR_DANCE=client,server,transport
      - CROSSDOCK_BEHAVIOR_SING=client,server,transport

alpha:
    image: breerly/hello-server
    ports:
        - 8080
    environment:
        - HELLO_PORT=8080
        - HELLO_MESSAGE=[{"status":"passed","output":"sup"}]

omega:
    image: breerly/hello-server
    ports:
        - 8080
    environment:
        - HELLO_PORT=8080
        - HELLO_MESSAGE=[{"status":"skipped","output":"sup"}]
